### ISSUE TITLE
Forgot to talk about the Bluetooth dongle?

### ISSUE THREAD

**Issue by dglaude** [recantha/EduKit3-Bluetooth#1]
In the "You will need:" no mention that you need either a Pi3 (with build-in Bluetooth) or a Bluetooth dongle to plug in a free USB slot (and if you have a PiZero you need "USB on the go" on the go adapter.)

So 3 options:
- Pi3
- Pi0 + USB OTG + Bluetooth dongle
- Any other Pi + Bluetooth dongle

For me, it would be the 2nd option that cost less (and I am not afraid to destroy a PiZero).

**Comment by recantha** [comment]
Oops. Thank you.
