### ISSUE TITLE
Option for shutting down pi?

### ISSUE THREAD

**Issue by Bobprogramming1234** [recantha/EduKit3-Bluetooth#2]
Great work, however could you add an optional shutdown script after the plus and minus buttons are pressed? This would be very helpful for a pi in headless mode

**Comment by recantha** [comment]
Hi!
Thanks for the feedback. You are, of course, correct. Preserving the SD card and everything is important.
I've updated wii_controller.py to add a system halt when the + and - buttons are pressed. I've also put in an optional line in the part where the pairing fails that you can uncomment if you want it to shutdown if it fails.

Hope this helps!

Mike

**Comment by Bobprogramming1234** [comment]
Thanks!!!
